# docker-compose.yml
version: '3.2'
services:
  web:
    tty: true
    container_name: sk-firebase
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    expose:
      - 3000
    command: npm run start
